export HISTSIZE=25
export PYENV_ROOT="$HOME/Library/Python"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
export NVIM=/root/.config/nvim
export PATH="/root/bin:$PATH"

alias ls='ls --color=auto -FG'
alias sl='ls'

PROMPT='%F{blue}%m%f@%F{cyan}%n%f:%F{green}%c%f $ '


#---------------------------------
#HISTORY SETTINGS
#---------------------------------
setopt HIST_IGNORE_SPACE
export HISTFILE=${HOME}/Library/Shell/zsh/.zsh_history
export SAVEHIST=100000
setopt hist_ignore_dups
