conf="$HOME/Library/Shell/zsh"

if [ -e "$conf/src/env" ];then
	source "$conf/src/env"
	echo "loaded environmental config file."
fi

if [ -e "$conf/src/pyrc" ];then
	source "$conf/src/pyrc"
	echo "loaded python config file."
fi

if [ -e "$conf/src/vim" ];then
	source "$conf/src/vim"
	echo "loaded vim config file."
fi


