#{{{ CUSTOM SETTING
export LIBRARY="$HOME/Library"

export STATE_PYENV=1
export STATE_VIM=1
export STATE_BIN=1
#}}}

conf="$LIBRARY/Shell/zsh"

if [ -e "$conf/src/env" ];then
	source "$conf/src/env"
	echo "loaded environmental config file."
fi

if [ -e "$conf/src/pyrc"  -a $STATE_PYENV -eq 1 ];then
	source "$conf/src/pyrc"
	echo "loaded python config file."
fi

if [ -e "$conf/src/vim" -a $STATE_VIM -eq 1 ];then
	source "$conf/src/vim"
	echo "loaded vim config file."
fi

if [ -e "$conf/src/bin" -a $STATE_BIN -eq 1 ];then
	source "$conf/src/bin"
	echo "append path"
fi

