export PYENV_ROOT="$HOME/Library/Python"
export PATH="$PYENV_ROOT/bin:$PATH"
export LIBRARY="$HOME/Library"
eval "$(pyenv init -)"
export NVIM=/root/.config/nvim
export PATH="$HOME/Library/bin:$PATH"
export PS1='\[\e[0;34m\]\u\[\e[0;37m\]@\[\e[0;36m\]\h:\[\e[0;32m\]\w \[\e[0;37m\]$ '

export HISTFILE="$LIBRARY/Shell/bash/bash_history"

alias ls='ls --color=auto -FG'
alias sl='ls'

